# Generated by Django 5.0.14 on 2026-04-24 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademiques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='departement')),
                ('initiale', models.CharField(max_length=50, null=True)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('postnom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('lieunaissance', models.CharField(max_length=50)),
                ('datenaissance', models.DateField()),
                ('sexe', models.CharField(max_length=2)),
                ('etat_civil', models.CharField(max_length=50, null=True)),
                ('nationalite', models.CharField(max_length=50, null=True)),
                ('nom_pere', models.CharField(max_length=50, null=True)),
                ('nom_mere', models.CharField(max_length=50, null=True)),
                ('province_origine', models.CharField(max_length=50, null=True)),
                ('territoire', models.CharField(max_length=50, null=True)),
                ('numero', models.IntegerField(null=True)),
                ('avenue', models.CharField(max_length=50, null=True)),
                ('nom_ecole', models.CharField(max_length=50, null=True)),
                ('section_suivi', models.CharField(max_length=50, null=True)),
                ('annee_diplome', models.CharField(max_length=50, null=True)),
                ('pourcentage_diplome', models.CharField(max_length=50, null=True)),
                ('numero_diplome', models.CharField(max_length=50, null=True)),
                ('activite_professionnelle', models.CharField(max_length=50, null=True)),
                ('premier_choix', models.CharField(max_length=50, null=True)),
                ('deuxieme_choix', models.CharField(max_length=50, null=True)),
                ('dossier', models.TextField(null=True)),
                ('photo', models.ImageField(upload_to='etudiant')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('telephone', models.IntegerField(null=True)),
                ('telephone_secondaire', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation', models.CharField(choices=[('J', 'Jour'), ('S', 'Soir')], max_length=1, null=True)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
                ('anneeacademique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anneeacademique', to='etudiantapp.anneeacademiques')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departement', to='etudiantapp.departements')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to='etudiantapp.etudiants')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='etudiantapp.promotions')),
            ],
        ),
        migrations.CreateModel(
            name='Communes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province', to='etudiantapp.provinces')),
            ],
        ),
        migrations.CreateModel(
            name='Quartiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commune', to='etudiantapp.communes')),
            ],
        ),
        migrations.AddField(
            model_name='etudiants',
            name='quartier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartier', to='etudiantapp.quartiers'),
        ),
    ]
