# Generated by Django 4.2 on 2025-10-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiantapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departements',
            name='description',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departements',
            name='image',
            field=models.ImageField(null=True, upload_to='departement'),
        ),
        migrations.AddField(
            model_name='promotions',
            name='description',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotions',
            name='image',
            field=models.ImageField(null=True, upload_to='promotion'),
        ),
        migrations.AlterField(
            model_name='departements',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
