# Generated by Django 4.2 on 2025-10-31 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiantapp', '0002_departements_description_departements_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotions',
            name='image',
        ),
    ]
