# Generated by Django 4.2 on 2025-10-31 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiantapp', '0003_remove_promotions_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotions',
            name='description',
        ),
    ]
