# Generated by Django 4.2 on 2025-11-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiantapp', '0004_remove_promotions_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='departements',
            name='initiale',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inscriptions',
            name='vacation',
            field=models.CharField(choices=[('J', 'Jour'), ('S', 'Soir')], max_length=1, null=True),
        ),
    ]
