# Generated by Django 5.0.14 on 2026-04-24 21:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiantapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('categorie', models.CharField(help_text='Ex: Événement, Académique, Campus', max_length=100)),
                ('auteur', models.CharField(default='Admin', max_length=100)),
                ('image', models.ImageField(upload_to='blog/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('description_courte', models.TextField(help_text="Introduction affichée sur la page d'accueil")),
                ('contenu', models.TextField(help_text="Contenu complet de l'article/événement")),
                ('citation', models.TextField(blank=True, help_text='Optionnel: Citation mise en évidence', null=True)),
                ('auteur_citation', models.CharField(blank=True, max_length=100, null=True)),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('heure', models.CharField(blank=True, help_text='Ex: 08h00 - 16h00', max_length=100, null=True)),
                ('entree', models.CharField(blank=True, help_text='Ex: Libre sur inscription', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('postnom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('fonction', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('photo', models.ImageField(upload_to='personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='AffectionPersonnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_affectation', models.DateField()),
                ('date_fin_affectation', models.DateField(blank=True, null=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiantapp.departements')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.personnel')),
            ],
            options={
                'verbose_name': 'AffectionPersonnel',
                'verbose_name_plural': 'AffectionPersonnels',
            },
        ),
    ]
