# Generated by Django 4.2 on 2026-03-04 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='degre',
        ),
        migrations.AddField(
            model_name='personnel',
            name='fonction',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.personnel')),
            ],
        ),
    ]
