# Generated by Django 4.2 on 2026-03-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_remove_personnel_degre_personnel_fonction_comite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
