# Generated by Django 5.0.14 on 2026-06-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0003_articles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='articles/fichiers/'),
        ),
    ]
