# Generated by Django 5.0.14 on 2026-04-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0003_alter_personnel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('categorie', models.CharField(help_text='Ex: Événement, Académique, Campus', max_length=100)),
                ('auteur', models.CharField(default='Admin', max_length=100)),
                ('image', models.ImageField(upload_to='blog/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('description_courte', models.TextField(help_text="Introduction affichée sur la page d'accueil")),
                ('contenu', models.TextField(help_text="Contenu complet de l'article/événement")),
                ('citation', models.TextField(blank=True, help_text='Optionnel: Citation mise en évidence', null=True)),
                ('auteur_citation', models.CharField(blank=True, max_length=100, null=True)),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('heure', models.CharField(blank=True, help_text='Ex: 08h00 - 16h00', max_length=100, null=True)),
                ('entree', models.CharField(blank=True, help_text='Ex: Libre sur inscription', max_length=100, null=True)),
            ],
        ),
    ]
