# Generated by Django 5.0.14 on 2026-06-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0004_articles_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='is_payant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articles',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
