# Generated by Django 5.0.14 on 2026-06-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0006_personnel_user_photo_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectionpersonnel',
            name='date_affectation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='auteur',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='titre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
